docToolchain/docToolchain

- README.adoc
For commands to be typed on the command line I recommend a "listing" block instead of an "example" block. This way line breaks are preserved and it looks more like a console. With the example block the current console example don't show at all on Github.
Also Asciidoctor known that "." just after a URL is not part of the URL. Therefore you don't need a blank there.
> update formatting of command line and link at end of sentence

- scripts/asciidoc2confluence.groovy
Before, something like this was not processed correctly:
```
[source,bash]
----
some text
----
```
Now, the language type will not be ignored but correctly added to the confluence macro.
With the above example, you will get a correct code block in confluence using the bash highlighting.
To achieve this, several steps were necessary:
1. Sanitize the codeblock from added XML syntax (i.e. `<span class="type">`, etc.)
2. skip in the general replacement block all code tags, that contain a language attribute
3. replace all code tags with the correct syntax
For further question, please write me (we can use german for a private conversation)
> Feature: language type for confluence

- scripts/ConfluenceConfig.groovy
- scripts/asciidoc2confluence.groovy
The text between the title and the first second level heading (the preamble) is put onto a separate page who's title is a hard-coded "arc42".
This PR allows users to override the page title for each input document.
> make title of page containing preamble configurable

- scripts/asciidoc2confluence.groovy
For the longish story see #49 
I've stripped all HTML markup from link texts now, seems to work well for our use case.
> make internal cross references work for Confluence pages

- scripts/asciidoc2confluence.groovy
Currently, it was not possible to reference online images (i.e. 'http://server/image'). The confluence script failed with an error.
This fix will check if the image source starts with 'http' and skip the upload to confluence and instead use another tag to correctly include online images.
Please test before merging, because my setup currently only includes one local image (which worked fine).
> [BUGFIX] Reference Online Images (Confluence)

- scripts/asciidoc2confluence.groovy
The current implementation does not respect the custom configuration of an image (i.e. the image width and the image alignment).
Those two attributes are parsed from the original and passed to confluence.
> Adopted image attributes _width_ and _align_ to confluence

- src/test/docs/test.adoc
I'm not sure how it worked for you, but it was failing for me as well as failed in CI without that change.
That $ ends up in the file path, which apparently confuses Linux or Mac, may be working on Windows.
> Fix failing test for PDF generation with PlantUML

- Config.groovy
- build.gradle
- gradle.properties
- scripts/asciidoc2confluence.groovy
- scripts/pandoc.gradle
- scripts/publishToConfluence.gradle
- src/test/config.groovy
Define new "docDir" property, which serves as a base for all other
configuration paths.
Support for PDF styles included with the contents, not with the tool.
Fix conversion to epub and docx.
Fix minor faults with paths.
This is meant to fix #88, I can now specify custom PDF style with my documents.
> Add support for configuration of PDF styles

- scripts/asciidoc2confluence.groovy
publishToConfluence task is now searching for all pages within the space matching fuzzily the expected title. Then the page with the title matching the expected one is chosen in case-insensitive way. Pages with similar but different titles are not affected, even if matched by fuzzy search from Confluence.
> Fix issue #15 - change of character case in headline of Confluence

- build.gradle
just updated some of the version numbers to the currently latest version.
didn't upgrade the log4j versions to the current betas
> fix #96 - updated version numbers

- docs/index.html
- scripts/asciidoc2confluence.groovy
- src/docs/manual/03_task_publishToConfluence.adoc
Two changes included:
* Support for re-writing `<mark>` elements when publishing to confluence, so they'll have the expected formatting
* Add section to docs to talk about how to configure CSS styles in Confluence (see #167)
* No; I'm open to working on such a test if you think it's worthwhile, but adding test coverage for the Confluence publishing support seems like it would require a fair amount of restructuring of the existing approach.
> CSS styling

- scripts/asciidoc2confluence.groovy
Most important update is changing the 'and' to 'with'.
'And' suggests a page with the same id en title already exists, but the limitation is only the confluence page title, the id the exception message is merely for assisting the user to find the duplicate page (title).
Also added some extra context about the Confluence limitation and  possibilities of docToolChain. This will save everyone time (who is less familiar with confluence or the tool)
> Improve exception message

- src/docs/manual/03_task_convertToDocx.adoc
Once again, the current docs is technically correct: the necessary info (pandoc, docx format) is there, but very easy to overlook.
> added hint to pandoc dep and formats in Config.groovy

- scripts/asciidoc2confluence.groovy
The MD5 for the localPage was calculated before the extraPageContent was prefixed to the localPage. Therefore the hashes didn't differ, if there weren't any other page changes in the local HTML.
With this change it is now possible to just change the extraPageContent banner and push it to Confluence.
> calculate localHash after prefixing extraPageContent

- src/docs/manual/01_introduction_and_goals.adoc
I've given the [Grazie grammar checking plugin](https://plugins.jetbrains.com/plugin/12175-grazie/) a test run on the first chapter. I also read up on "which" vs. "that" and changed some of them according to this website: https://www.grammarly.com/blog/which-vs-that/. Please double check.
> putting the grammar plugin gratie to the test

- Config.groovy
- src/docs/manual/03_task_publishToConfluence.adoc
- template_config/scripts/ConfluenceConfig.groovy
Source #375 
This fixed the documentation to clarify that the `ancestorId` shall be a of type `String`. 
I did not build the docs for several reasons:
* the `feedback.adoc` cannot be included (on every page), didn't find out why (it was already an issue when I generated docs based on master, also in the published version) - and that would leave all generated HTML with my local path I don't want in the repo
* the doc generation changed a lot of HTML properties - not sure why (I'm on Windows btw.), e.g. 
```
-<img src="images/demoPlantUML.png" alt="demoPlantUML" width="246" height="236">
+<img src="images/demoPlantUML.png" alt="demoPlantUML" width="231" height="236">
```
> Clarified usage and type of ancestorId #375

- .travis.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- gradlew.bat
- scripts/exportExcel.gradle
- scripts/exportJiraIssues.gradle
- scripts/exportMarkdown.gradle
- scripts/publishToConfluence.gradle
- src/test/testData/excel/Sample.xlsx/ColAndRowSpan.adoc
Doing this while getting more familiar with the toolchain.
Updating asciidoctor dependencies to versions that play well together while not breaking anything seems to be not trivial or even requires some task code changes due to API updates in:
* asciidoctor-gradle-plugin
* asciidoctor.convert
* asiidoctorj-pdf
* asciidoctorj-diagram
Seems to be an interesting task to explore to see how everything plays together. But that would anyway go via different PR.
> Update remaining dependency versions except the asciidoctor related ones

- scripts/asciidoc2confluence.groovy
rewriteCodeBlock rewrites callouts as comments in the code.
Issue: #315
> Handle callouts on publishToConfluence

- Config.groovy
- scripts/publishToConfluence.gradle
- src/docs/manual/03_task_publishToConfluence.adoc
- src/docs/manual/05_contributors.adoc
Pullrequest for suggestion from [Issue 405](https://github.com/docToolchain/docToolchain/issues/405)
Adds a block, that modifies the config if `confluence.credentials` is empty.
Takes the variables `confluenceUser` and `confluencePassword` from the build environment (see [gradle manual](https://docs.gradle.org/current/userguide/build_environment.html)) to generate a new credentials string and insert it into the confluence object befor binding it.
> Added Credentials Fallback based on gradle properties to publishToConfluence

- build.gradle
Changed testCompile to testImplementation to make the build.gradle compatible with upcoming gradle version. I was not able to find out, which the minimum gradle version is, which works with testImplemenation, however, gradle 4.6 seems to include it. https://docs.gradle.org/4.6/release-notes.html
"Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1/userguide/command_line_interface.html#sec:command_line_warnings"
> Update build.gradle testCompile soon to be depreca

- scripts/asciidoc2confluence.groovy
As reported in issue  #428, the configuration of publishToConfluence is not used for the APIkey representation in the HTTP header. So, requests were rejected in case it is required with reason: missing authentication credentials.
This pull request fixes the issue by adding the apikey key/value pair if the config parameter: 'config.confluence.apikey' is set, otherwise no additional header field is added and previous behaviour is retained.
Documentation not affected.
> Fix for #428 publishToConfluence authentication failure

- Config.groovy
- scripts/asciidoc2confluence.groovy
- src/docs/manual/03_task_publishToConfluence.adoc
What i actually added are 2 configuration options.
1st to enable attachments for confluence
2nd to tell the folder name of the attachments.
* [ x] Does your PR affect the documentation?
* [x ] If yes, did you update the documentation or create an issue for updating it?
-------
**Please be so kind to do a manual verification, that the step works after integration into the official repository. I had limitations on this side. On a copy of the adapted …
> Added attachment support

- Config.groovy
- scripts/exportEA.gradle
- scripts/exportEAP.vbs
- src/docs/manual/03_task_exportEA.adoc
As described in issue #439, the export does not work as expected in case the docToolchain repository is not used as a submodule, but used as a standalone tool. In this case the configured docDir wasn't used as base directory.
This is fixed by this pull request. 
In addition the path to export the diagrams can be set as an optional parameter. Same for the path where to look for eap or eapx project files. Both paths are relative to the docDir path.
The sample Config.groovy and documentation is updated accordingly.
A method is added tp clean the filenames in case it contains invalid characters.
> Add parameter exportPath and searchPath to exportEA module

- .ci.sh
- .travis.yml
- README.adoc
- build.gradle
- scripts/AsciiDocBasics.gradle
- scripts/exportContributors.gradle
This PR leaves all existing documentation in place. It adds to the build process the feature to publish the master content automatically to the GitHub pages. This will avoid errors like this currently present on the public site: 
fixes #260 (although not moving to Netlify, but keeping Travis and GitHub pages)
This worked fine on my test repository; some with access to the the docToolchain repo would need to update the .travisci.yml to make this work and add a GitHub token. As this is an organization, it would probably be best to have a CI-User in the organization who's access is limited to the organization.
maybe fixes #465 as well (the part "problem that the result of exportContributors gets deleted afterwards"):
This fixes the problem that on travis CI the contributors where never …
> enable TravisCI to publish the docs to the website

- Config.groovy
- scripts/exportEA.gradle
- scripts/exportEAP.vbs
- src/docs/manual/03_task_exportEA.adoc
This pull request refers to issue #490
It is a new feature of the exportEA script.
It enables the exportEA script to run an export of the EnterpriseArchitect project glossary.
The output format can be configured to be according to asciidoc notation.
The types of elements used to generate the exported asciidoc formatted is configurable.
A new glossary subfolder will be added to the exportPath.
Multiple glossary files will be generated in case of multiple project files are found.
One global glossary file is generated by merging all single glossary files.
The generated  files can be used as part of the resulting documentation depending in individual format of the user.
Documentation is added and reformatted manual of exportEA.
> Add new exportEA feature to export project glossary filtered & sorted

- scripts/exportOpenApi.gradle
It avoid unnecessary error logs in case an export specific configuration is not set.
Instead an info log level is set to at least show the log in case calling exportOpenAPI with --info.
> Lower loglevel from error to info in case openAPI spec is not set

- Config.groovy
- scripts/exportEA.gradle
- scripts/exportEAP.vbs
- src/docs/manual/03_task_exportEA.adoc
This PR fulfills the new feature request #497 
It enables the export of some diagram attributes as part of the script exportEA. 
If the new configuration parameter is not set, the previous behaviour is left unchanged.
Following attribute placeholders are supported with this PR:
%DIAGRAM_AUTHOR%, %DIAGRAM_CREATED%, %DIAGRAM_GUID%, %DIAGRAM_MODIFIED%, %DIAGRAM_NAME%.
and filled with information read from EA project.
The diagramAttributes string can make use of none, one, many or all of this placeholders to format a resulting text block being included in the documentation.
** yes, as a new configuration update
** exportEA manual updated
> Add new feature to export attributes of a EA diagram as a separate file

- scripts/AsciiDocBasics.gradle
As discussed previously by mail a change introduced in PR #476 print **all** config keys **and their values** to the console when running with `--info`. This includes the Confluence and Jira Creds (Username + Password Base64-encoded). 
Through these changes secrets can appear in build logs unexpectedly.
Instead of reverting the change to the config printing (i think it's usefull for debugging), this PR introduces a blacklist of config key name fragments. If a key that is to be printed contains any of the defined fragments, '********' ist printed instead of the config's value. 
This solution providing a middleground between not printing the config and exposing secrets. Though should it be merged adds a blacklist, that needs to be kept up to date when new secrets are added to the config. …
> added saveguard to not print secrets to the console

- scripts/exportEAP.vbs
This pull request fixes the issue #450. It adds the export of notes that are found for the diagram itself.
Without it, all notes found on elements used by the diagram are exported only.
As it requires to start the notes on elements with {adoc: to be exported, it is the same for diagram notes.
If the tag is not found at the beginning of a note, the note is not going to be exported.
There was no need to update the documentation of exportEA.
I created this pull request as a representative of AndreaMcls.
> Add the export of notes found on an EA diagram itself.

- scripts/exportEAP.vbs
- src/docs/manual/03_task_exportEA.adoc
Both project accessed by database connection and by local EA project files should work in parallel.
First implementation was exclusively database or local files. 
Got several complains because of this and therefore I checked parallel support of both types and there is no issue supporting this.
Avoiding collisions in case of multiple projects in parallel should be managed by the projects itself.
Usually differently named root package should be sufficient.
I adopted documentation for exportEA script.
Test and feedback were positive until now.
> Add support of multiple EA project locations in parallel 

- scripts/exportEAP.vbs
This pull request fixes bug #529.
The script exportEA supports export of diagram attributes like author, name and modified date.
Because of a bug in the script, all diagrams gets the same attributes - the attributes of the first read diagram.
Sorry for this. I have to be more careful with merges in future.
Additionally, I introduced the const 'ForWriting'. By this, the files written are newly created and existing content will be removed. Previously used 'ForAppending' is not causing direct errors, but is not the intended functionality. Furthermore, in case same name is used for multiple diagrams, the last exported diagram is available only, but because of appending the attributes to file, the attributes of all diagrams with the same name were added.
> Fix writing of diagram attributes using exportEA

- Config.groovy
- scripts/asciidoc2confluence.groovy
- src/docs/manual/03_task_publishToConfluence.adoc
- src/docs/manual/05_contributors.adoc
- template_config/Config.groovy
**Attention**: I haven't "published" the docs yet. May be it makes sense to publish them after the PR gets merged ?!
Created [Issue](https://github.com/docToolchain/docToolchain/issues/559#issue-838043418)
No, I didn't. I run the unit tests locally to make sure that nothing is broken. Then tested my feature "manually" (by configuring accordingly and running publishToConfluence) since it's about introducing a new  macro for confluence. Didn't find Confluence integration …
> Add support for another OpenAPI Confluence macro

- scripts/exportEAP.vbs
As described in bug #570, with newer version of Enterprise Architect the script exportEA hangs while waiting for termination of the background process. To trigger this, the Repository API offers the Exit() method. 
Reference text: "Notes: Shuts down Enterprise Architect immediately. Used by .NET programmers where the garbage collector does not immediately release all referenced COM objects."
After adding this call, the script automatically proceeds until it ends successfully. It is tested with online connections and local eap files (even with combinations of both).
As this bug prevents us from periodical, automatic document generation, this pull request is from importance for us.
> Call Exit() of repository class to terminate the EA process on demand.

- scripts/AsciiDocBasics.gradle
The commit
97df9b9 scripts/AsciiDocBasics.gradle: fix inline plantuml referencing
introduces same path for all backends to save generated images from inline
plantUML code.  Unfortunately, it introduces a bug for Concluence backends
and amplifies a bug for the HTML5 backend.
This commit moves the plantUMLDir back to html5 and pdf backend, which should
avoid harming Confluence backend at all. Further, the value for the html5
backend is computed to a relative path for deploying the entire directory
structure to various locations.
https://github.com/docToolchain/docToolchain/issues/582 should be fixed by
this change.
Signed-off-by: Jens Rehsack <sno@netbsd.org>
To "publish" it, execute `./gradlew exportContributors && …
> scripts/AsciiDocBasics.gradle: fulfill different plantUML path requirements by backends

- scripts/exportEAP.vbs
When notes are exported there is no need to normalize the string.
Instead it is rather confusing when reading the notes to see e.g.
_dev_i2c instead of /dev/i2c.
Signed-off-by: Rosi2143 <Schrott.Micha@web.de>
> Use real name for elements when exporting notes
