docToolchain/docToolchain

scripts/ConfluenceConfig.groovy
scripts/asciidoc2confluence.groovy

allow optional extra content to be added to each published page

---

scripts/asciidoc2confluence.groovy

promote headers in sect2 Confluence pages as well

---

scripts/asciidoc2confluence.groovy

see #53 
This works for us, but there may be some cases that the changes miss, see the discussion inside the issue itself.

Fix code block stackoverflow

---

scripts/asciidoc2confluence.groovy

in #50 I introduced the `realTitle` closure and overlooked one place where it should be used

overlooked one case, where realTitle should be used

---

scripts/asciidoc2confluence.groovy

sort child pages by creation in children macro

---

scripts/asciidoc2confluence.groovy

This might prevent problems like #25 in the future.

deal with descriptions lists with unbalanced dt/dd elements

---

Config.groovy
build.gradle
gradle.properties
scripts/exportChangelog.gradle
scripts/exportJiraIssues.gradle
scripts/htmlSanityCheck.gradle
scripts/pandoc.gradle
src/docs/manual/02_install.adoc
src/test/groovy/docToolchain/exportChangeLogSpec.groovy

First attempt at #71, tested with generating HTML and PDF on MacOS.
I'm new to gradle and groovy, so feel free to comment.

Add custom configuration.

---

src/docs/manual/02_install.adoc
src/docs/manual/03_task_exportExcel.adoc
src/docs/manual/03_task_generateDeck.adoc
src/docs/manual/03_task_generateHTML.adoc
src/docs/manual/03_task_generatePDF.adoc
src/docs/manual/03_task_htmlSanityCheck.adoc
src/docs/manual/03_tasks.adoc
src/docs/manual/04_further_reading.adoc
src/docs/manual/05_contributors.adoc

This PR contributes small fixes to the manual (typos, grammer, capitalization, slight rewording).

Small fixes to the documentation

---

build.gradle

#96 added dependency to resolve problem with windows 10 and PDF

---

.gitignore
build.gradle
docs/index.html
src/docs/manual.adoc
src/docs/manual/05_contributors.adoc
src/docs/manual/06_Frequently_asked_Questions.adoc

did some work on the documentation, mainly newly added FAQ section

Updated docs

---

scripts/asciidoc2confluence.groovy

This solution is throwing an exception, which leaves the page possible half-updated, but I think it's better then "stealing" pages and overriding them.

Fix #57 by avoiding hijacking Confluence pages alredy existing

---

scripts/asciidoc2confluence.groovy

Indeed we need some automatic tests for Confluence export, the previous fix has broken export in case of ancestorId missing in the configuration.

Fix of previous fix for case of empty parent page

---

docs/index.html
src/docs/manual/03_task_exportVisio.adoc

Fix of issue 120 by fixing some typos

---

docs/index.html
init.gradle
src/docs/manual/02_install.adoc

Fix for #137 making target directory mandatory for initialization

---

build.gradle
docs/index.html
init.gradle
src/docs/manual.adoc
src/docs/manual/01_introduction_and_goals.adoc
src/docs/manual/02_install.adoc
src/docs/manual/03_task_convertToDocx.adoc
src/docs/manual/03_task_convertToEpub.adoc
src/docs/manual/03_task_dependencyUpdates.adoc
src/docs/manual/03_task_exportChangeLog.adoc
src/docs/manual/03_task_exportEA.adoc
src/docs/manual/03_task_exportExcel.adoc
src/docs/manual/03_task_exportJiraIssues.adoc
src/docs/manual/03_task_exportPPT.adoc
src/docs/manual/03_task_exportVisio.adoc
src/docs/manual/03_task_generateDeck.adoc
src/docs/manual/03_task_generateDocBook.adoc
src/docs/manual/03_task_generateHTML.adoc
src/docs/manual/03_task_generatePDF.adoc
src/docs/manual/03_task_htmlSanityCheck.adoc
src/docs/manual/03_task_publishToConfluence.adoc
src/docs/manual/03_tasks.adoc
src/docs/manual/04_further_reading.adoc
src/docs/manual/06_Frequently_asked_Questions.adoc
src/docs/manual/07_tutorial.adoc

#147 updated docs

---

Config.groovy
build.gradle
docs/index.html
scripts/AsciiDocBasics.gradle
scripts/exportChangelog.gradle
src/docs/customKeymap.adoc
src/docs/manual.adoc
src/docs/manual/03_task_convertToDocx.adoc
src/docs/manual/03_task_convertToEpub.adoc
src/docs/manual/03_task_exportChangeLog.adoc
src/docs/manual/03_task_exportJiraIssues.adoc
src/docs/manual/03_task_exportPPT.adoc
src/docs/manual/03_task_exportVisio.adoc
src/docs/manual/03_task_generateDeck.adoc
src/docs/manual/03_task_generateDocBook.adoc
src/docs/manual/03_task_generateHTML.adoc
src/docs/manual/03_task_generatePDF.adoc
src/docs/manual/03_task_htmlSanityCheck.adoc
src/docs/manual/03_task_publishToConfluence.adoc
src/test/config.groovy
src/test/config_without_revealjs.groovy
template_config/Config.groovy

This PR cleans up the main build file which makes it easier to incorporate docToolchain directly with existing projects.
yes, docs should be ok. Even fixed some other issues.
Created another issue for creating some tutorials.
No, because there is no new functionality. But the ones still run fine.
2. [X] Does your submission pass all tests? (see travis check)

#145 moved asciidoc tasks to script plugin

---

scripts/asciidoc2confluence.groovy

fix escaping of ampersand in Confluence code blocks

---

docs/index.html
src/docs/manual/02_install.adoc
src/docs/manual/03_task_convertToDocx.adoc
src/docs/manual/03_task_convertToEpub.adoc
src/docs/manual/03_task_dependencyUpdates.adoc
src/docs/manual/03_task_exportChangeLog.adoc
src/docs/manual/03_task_exportEA.adoc
src/docs/manual/03_task_exportJiraIssues.adoc
src/docs/manual/03_task_exportPPT.adoc
src/docs/manual/03_task_generateHTML.adoc
src/docs/manual/03_task_generatePDF.adoc
src/docs/manual/03_task_htmlSanityCheck.adoc

fix for #149

---

scripts/pandoc.gradle

Changed behavior, that not first docbook file is converted, instead script searches for epub and docx. These convert to docbook and then to the selected format.
Hi, don't know if these affects documentation. I use that script in one of my ci/cd scripts (which I will show on Froscon), so I want give you back the update.

Reads from config.groovy all docx/epub files

---

scripts/exportChangelog.gradle
src/test/config_pdf.groovy
src/test/groovy/docToolchain/GeneratePdfSpec.groovy
src/test/pdfTheme/custom-theme.yml

had to fix the test configuration. don't know why it was broken...

fix #186 pdf tests are working again

---

src/test/dtc-int-test.ah

Unfortunately I am not able to create the proposed /bash folder

docToolchain Integration Test

---

src/docs/manual/06_Frequently_asked_Questions.adoc

Added a Known Issue section to '06_Frequently_asked_Questions.adoc' for the error: 'Failed to create MD5 hash for file content.'
* [Y ] Does your PR affect the documentation?
* [Y ] If yes, did you update the documentation or create an issue for updating it?

Added a Known Issue section

---

scripts/ConfluenceConfig.groovy

Fix example config of extraPageContent

---

Config.groovy
template_config/scripts/ConfluenceConfig.groovy

Expended the input documentation with the possibilities that the current implementation already has.
This is very useful for first time users and users that don't look in the underlying code.
Making these configuration possibilities obvious, can attract more users in selecting this product.

Improve configuration explanation for users

---

src/docs/manual/03_task_exportPPT.adoc

added windows only hint for task exportPPT

---

README.adoc

Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/doctoolchain❤️
It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [more info](https://github.com/opencollective/opencollective/wiki/Github-banner). See how it looks on this [repo](https://github.com/apex/apex#backers).
You can also add a postinstall script to let people know after npm|yarn install that you are welcoming donations (optional). [More info](https://github.com/OpenCollective/opencollective-cli)
You can …

Activating Open Collective

---

scripts/exportContributors.gradle
src/docs/manual/05_contributors.adoc

Again:
very naive implementation.
does not support i18n
not tested

calculate minutes to read (append instead of (over)write)

---

scripts/asciidoc2confluence.groovy

see discussion at
https://github.com/docToolchain/docToolchain/issues/281

creating an not prettyPrinted Document for sect2 pages fixes the bug

---

bin/doctoolchain.bat

After adding quotes around -Pdocdir the script doctoolchain works a little bit better if there is a blank in the docdir path. (https://github.com/docToolchain/docToolchain/issues/319#issue-450049615)

Update doctoolchain.bat: (issue #319)

---

src/docs/manual/03_task_exportDrawIo.adoc

I have tried this process and it works well, but the original instruction set left a few too many questions.
I've proposed a workflow that folks can use to continue using draw.io.
I have not published the file just in case changes are required.
Not as yet. I will do that later on.
I have not published the file just in case changes are required.
I have added a note into #194 to re-build the docs once the change is improved.

Proposed an editing workflow for #194

---

src/docs/manual/02_install.adoc

Make sure to go into the correct directory before doing rm

---

bin/doctoolchain

Add missing quotes to support spaces in path

---

src/docs/manual/03_task_publishToConfluence.adoc

Fixed typos in 03_task_publishToConfluence.adoc

---

.editorconfig
CONTRIBUTORS.adoc
src/docs/manual/05_contributors.adoc

#365
No docs changes, no tests, no code changes, just an .editorconfig

add details to .editorconfig

---

scripts/prependFilename.gradle

change the description for prependFilename to reflect the real behavior of the script

change description for prependFilename

---

Config.groovy
docs/htmlchecks/index.html
docs/index.html
scripts/asciidoc2confluence.groovy
src/docs/manual/03_task_publishToConfluence.adoc
src/docs/manual/05_contributors.adoc

yes
The manual is updated in the PR
Yes
Not applicable
Yes
Yes, i had to do it manually as Windows doesn't run .sh

Fix for #369

---

src/docs/manual/03_task_collectIncludes.adoc

fix typo /src/jave to /src/java

fix typo in path

---

scripts/AsciiDocBasics.gradle
src/docs/manual/05_contributors.adoc

* [N] Does your PR affect the documentation?
* [NA] If yes, did you update the documentation or create an issue for updating it?
* [336] Welcome to the list of contributors! If you have any questions, feel free to ask them by creating a new issue
* [Y] Have you added your name to the list of [contributors.adoc](https://github.com/docToolchain/docToolchain/blob/master/src/docs/manual/05_contributors.adoc)?
* [Y, no changes] Did you build the docs and copy them to …

Fix custom fonts

---

.ci.sh
.gitignore
.travis.yml
bin/doctoolchain
build.gradle
copyDocs.sh
gradle/wrapper/gradle-wrapper.properties
init.gradle
src/docs/manual/05_contributors.adoc

While getting more familiar with the toolchain, I put together some commands from the documentation into a script called `.ci.sh`, which this way serve as extended CI steps with the characteristics of integration/end2end tests. It also checks that the .gitignore is complete and shows if there are some dependency updates. The script runs via CI and locally (no copying of many commands from `.travis.yml` to reproduce locally).
The PR also updates the init.gradle, the gradle wrapper and the gradle versions plugin. Shellcheck for shell scripts is introduced and the findings are resolved.
This is done in preparation of updating all the plugins, dependencies and submodules to newer versions while testing that they play well together.
The source of the documentation can be found in …

Extend CI steps, gradle update, other small updates

---

build.gradle
docs/index.html
init.gradle
scripts/htmlSanityCheck.gradle
src/docs/exportMarkdownDocs.md
src/docs/manual/03_task_generatePDF.adoc
src/docs/manual/05_contributors.adoc
src/test/docs/exportMarkdownDocs.md

* [N] Does your PR affect the documentation?
* [Y] If yes, did you update the documentation or create an issue for updating it?
- update htmlSanityCheck to latest released version 1.1.3
- update ben-manes.versions to latest released version 0.27.0
- fix some URLs in the docs (htmlSanityCheck findings)
* [Y ] Have you added your name to the list of [contributors.adoc](https://github.com/docToolchain/docToolchain/blob/master/src/docs/manual/05_contributors.adoc)?

Update htmlSanityCheck & fix some URLs in the docs

---

docs/index.html
gradle.properties
scripts/AsciiDocBasics.gradle
scripts/pandoc.gradle
src/docs/manual.adoc
src/docs/manual/03_task_convertToDocx.adoc
src/docs/manual/03_task_createReferenceDoc.adoc

- add new task createReferenceDoc to create a reference docx with custom styles
- update task convertToDocx to optionally use a reference docx specified in config.groovy
- update manual and docs
* [Y] Does your PR affect the documentation?
* [Y] If yes, did you update the documentation or create an issue for updating it?
1. [N] Did you create new tests for your submission?
2. [Y] Does your submission pass all tests? (see travis check)
* [N] Have you written new tests for your core changes, as applicable?
* [Y] Have you successfully ran tests with your changes locally?
* [Y] Did you build the docs and copy them to the `/docs` folder?
* [N] If not, did you create an issue for doing so?

new task createReferenceDoc to create a reference docx & update convertToDocx to optionally use a reference docx

---

.travis.yml
gradle/wrapper/gradle-wrapper.properties

Also adding OpenJDK13 to travis test matrix.

Update gradle wrapper to 6.0.1 to support Java 13

---

Config.groovy
scripts/exportEA.gradle
scripts/exportEAP.vbs
src/docs/manual/03_task_exportEA.adoc
src/docs/manual/05_contributors.adoc

There is a bug in feedback.adoc which I did not fix. Because of this, I didn't generated/copied the HTML files, even the documentation is done in '03_task_exportEA.adoc'.

Issue #426: Add parameter for EA database connection and filter for packages to exportEA script

---

scripts/asciidoc2confluence.groovy

This PR suggests a fix to issue #487. The fix works in our environment, where a proxy is being used.
With this PR I intend to create awareness for the issue and suggest a possible solution. However, I did not have time to add automated regression tests or do a thorough analysis of the code base. So it might be needed that someone additionally checks for any side effects.

Fix issue with proxy while updating images

---

build.gradle
gradle.properties
scripts/AsciiDocBasics.gradle
scripts/exportExcel.gradle
scripts/exportJiraIssues.gradle
scripts/exportJiraSprintChangelog.gradle
scripts/exportMarkdown.gradle
scripts/exportOpenApi.gradle
scripts/htmlSanityCheck.gradle
scripts/publishToConfluence.gradle

fix #502 allow to override maven repository

---

Config.groovy
scripts/htmlSanityCheck.gradle

Create additional properties in Config.groovy and just give them to htmlSanityCheck.

docToolchain#507 add properties for htmlSanityCheck

---

RELEASE.adoc
build.gradle
changelog.adoc

- description of the release process
- updated the changelog that all changes which have been done after 1.3.0 can be seen
- copied "createDist" from the ng-branch because we may need it for releasing

[519] - describe release process & update changelog for next release

---

src/docs/manual/05_contributors.adoc

Txemanu added as contributor

---

scripts/AsciiDocBasics.gradle

Use `plantUMLDir` for all AsciidoctorTask to avoid issues like
...
> Task :generateHTML
Converting /data/Projects/FBT/Amana/TTH/TTH-Arch/doctoolchain_demo.adoc
Converting /data/Projects/FBT/Amana/TTH/TTH-Arch/arc42-template.adoc
src/03_system_scope_and_context.adoc: line 59: Failed to generate image: Permission denied - /seq1.png
...
when fixing
...
> Task :generatePDF
Converting /data/Projects/FBT/Amana/TTH/TTH-Arch/doctoolchain_demo.adoc
Converting /data/Projects/FBT/Amana/TTH/TTH-Arch/arc42-template.adoc
image to embed not found or not readable: /data/Projects/FBT/Amana/TTH/TTH-Arch/images/seq1.png
...
by using `plantUMLDir` on embedding plantuml diagram like:
.ExternVisibleWorkflow
[plantuml,{plantUMLDir}/seq1,png]
----
actor User
participant Browser
...
----
Signed-off-by: Jens …

scripts/AsciiDocBasics.gradle: fix inline plantuml referencing

---

scripts/AsciiDocBasics.gradle
src/docs/manual/03_task_generateHTML.adoc
src/docs/manual/05_contributors.adoc
src/test/docs/test.adoc
src/test/docs/test2.adoc
src/test/testPdfDefaultTheme/testPdfDefaultThemeDocs/test2.adoc
src/test/testPdfSpecificTheme/testPdfSpecificThemeDocs/test2.adoc

Update asciidoc pdf and diagram (plantUML) dependency versions to fix #526

Update asciidoc diagram (plantUML) dependency version

---

Config.groovy
scripts/exportEA.gradle

Allow absolute path - Fix #609

---

gradle.properties
scripts/AsciiDocBasics.gradle
scripts/exportExcel.gradle
scripts/exportJiraIssues.gradle
scripts/exportJiraSprintChangelog.gradle
scripts/exportMarkdown.gradle
scripts/exportOpenApi.gradle
scripts/htmlSanityCheck.gradle
scripts/publishToConfluence.gradle

Tested it with credentials section and empty credentials with the default mavenRepository - it just worked, so no if-groovy block required.

Add maven credentials #612

---

src/docs/landingpage.gsp

Fixed some spelling errors on landing page

---

scripts/GlobalReferences.gradle

Globale Referenzen
